<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Mr.Mrs.Ms</name>
   <tag></tag>
   <elementGuidId>e8bf55d5-d315-489f-953b-008d53e75fc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='adultForm0']/div/div/div[2]/div/div/div/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select.r-30o5oe.r-1niwhzg.r-1yadl64.r-1p0dtai.r-t1w4ow.r-ubezar.r-majxgm.r-1pi2tsx.r-1r74h94.r-135wba7.r-crgep1.r-orgf3d.r-1ny4l3l.r-10paoce.r-u8s1d.r-3mc0re.r-ipm5af.r-34rx7k.r-417010</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>08b0a225-491d-46ec-a3e2-841adb2de87d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>r-30o5oe r-1niwhzg r-1yadl64 r-1p0dtai r-t1w4ow r-ubezar r-majxgm r-1pi2tsx r-1r74h94 r-135wba7 r-crgep1 r-orgf3d r-1ny4l3l r-10paoce r-u8s1d r-3mc0re r-ipm5af r-34rx7k r-417010</value>
      <webElementGuid>8f3d314f-de0f-469b-9628-17544c60ff99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mr.Mrs.Ms.</value>
      <webElementGuid>e1a05ff1-4ad1-4e0d-9b2f-99ff15922827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;adultForm0&quot;)/div[@class=&quot;css-1dbjc4n r-14lw9ot r-kdyh1x r-da5iq2 r-bztko3&quot;]/div[@class=&quot;css-1dbjc4n r-1ihkh82 r-bztko3&quot;]/div[@class=&quot;css-1dbjc4n r-14lw9ot&quot;]/div[@class=&quot;css-1dbjc4n r-mhe3cw&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n r-1awozwy r-18u37iz r-eu3ka r-1wtj0ep r-1ny4l3l r-10paoce r-edyy15&quot;]/select[@class=&quot;r-30o5oe r-1niwhzg r-1yadl64 r-1p0dtai r-t1w4ow r-ubezar r-majxgm r-1pi2tsx r-1r74h94 r-135wba7 r-crgep1 r-orgf3d r-1ny4l3l r-10paoce r-u8s1d r-3mc0re r-ipm5af r-34rx7k r-417010&quot;]</value>
      <webElementGuid>fc902b02-e37a-41e5-b7a7-59ddfaf1757a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='adultForm0']/div/div/div[2]/div/div/div/select</value>
      <webElementGuid>dc48994c-a2be-4e67-887f-46ce26d0044e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::select[1]</value>
      <webElementGuid>ef55e05d-1bd4-4948-817b-05b2724e12d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/preceding::select[1]</value>
      <webElementGuid>b3a35e77-724b-4974-ad9a-c77b07941e5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div[2]/div/div/div/select</value>
      <webElementGuid>e134c3ff-7e32-429c-bde5-015a6bd69135</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = 'Mr.Mrs.Ms.' or . = 'Mr.Mrs.Ms.')]</value>
      <webElementGuid>6be2c5c5-68a5-48bf-93fa-fe293926b234</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
