<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Airport loc (select)</name>
   <tag></tag>
   <elementGuidId>0cee68e5-644b-4f36-b037-787ba9c7091f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='RENTAL_DROPOFF_LOCATION']/div/div/div[5]/div[2]/div/div/div/div/div[2]/div/div/div/div[3]/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-1dbjc4n.r-1vjbqqu.r-1q52ik8.r-qklmqi.r-1loqt21.r-18u37iz.r-1wtj0ep.r-ymttw5.r-5njf8e.r-1otgn73.r-1i6wzkk.r-lrvibr.r-13qz1uu > div.css-1dbjc4n.r-1777fci.r-19u6a5r > div.css-901oao.css-bfa6kz.r-1naam9t.r-kdyh1x.r-rs99b7.r-t1w4ow.r-1enofrn.r-majxgm.r-1cwl3u0.r-vjwmdu.r-1pn2ns4.r-fdjqy7</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0002bfb6-5df8-43b6-94e9-4092b22b4603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>e0805827-2082-4c31-bc5a-81a91e15ffcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-901oao css-bfa6kz r-1naam9t r-kdyh1x r-rs99b7 r-t1w4ow r-1enofrn r-majxgm r-1cwl3u0 r-vjwmdu r-1pn2ns4 r-fdjqy7</value>
      <webElementGuid>7ed36bdc-2daf-44ad-bc2c-07a0c96e94e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>undefined-label</value>
      <webElementGuid>f836156b-5078-4d5b-b7ba-88b223ce4ddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Airport</value>
      <webElementGuid>755309a5-c6e1-437d-b684-e31015999348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RENTAL_DROPOFF_LOCATION&quot;)/div[@class=&quot;css-1dbjc4n r-14lw9ot r-kdyh1x r-b4qz5r r-1ifxtd0 r-nsbfu8 r-184en5c&quot;]/div[@class=&quot;css-1dbjc4n r-eqz5dr&quot;]/div[@class=&quot;css-1dbjc4n r-14lw9ot r-kdyh1x r-da5iq2&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n r-391gc0 r-nsbfu8&quot;]/div[@class=&quot;css-1dbjc4n r-184en5c&quot;]/div[@class=&quot;css-1dbjc4n r-14lw9ot r-1e4vmmq&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n r-14lw9ot r-1wh2hl7 r-e65k4z r-b4qz5r r-1dqxon3 r-u8s1d r-1e4vmmq&quot;]/div[@class=&quot;css-1dbjc4n r-150rngu r-eqz5dr r-16y2uox r-1wbh5a2 r-11yh6sk r-1rnoaur r-1sncvnh&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n r-1vjbqqu r-1q52ik8 r-qklmqi r-1loqt21 r-18u37iz r-1wtj0ep r-ymttw5 r-5njf8e r-1otgn73 r-1i6wzkk r-lrvibr r-13qz1uu&quot;]/div[@class=&quot;css-1dbjc4n r-1777fci r-19u6a5r&quot;]/div[@class=&quot;css-901oao css-bfa6kz r-1naam9t r-kdyh1x r-rs99b7 r-t1w4ow r-1enofrn r-majxgm r-1cwl3u0 r-vjwmdu r-1pn2ns4 r-fdjqy7&quot;]</value>
      <webElementGuid>a7da6dc3-3c33-4966-9807-16b7d4be40d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RENTAL_DROPOFF_LOCATION']/div/div/div[5]/div[2]/div/div/div/div/div[2]/div/div/div/div[3]/div[2]/div</value>
      <webElementGuid>33d92ab6-2c59-41f8-86d5-fc9f77f57051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Benda, Cengkareng, West Jakarta, Jakarta, Indonesia, Southeast Asia, Asia'])[3]/following::div[2]</value>
      <webElementGuid>2c74591d-a4cc-4cd8-9ab9-b0cab215a8dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Halim, Makasar, East Jakarta, Jakarta, Indonesia, Southeast Asia, Asia'])[2]/preceding::div[1]</value>
      <webElementGuid>27b17e55-649c-47ae-84fe-27a08b60c76a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[5]/div[2]/div/div/div/div/div[2]/div/div/div/div[3]/div[2]/div</value>
      <webElementGuid>d343f3f5-6606-47b1-96f5-df467ea8b74b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Airport' or . = 'Airport')]</value>
      <webElementGuid>84db0dc1-6746-4ba5-874c-fe1b706831eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
