<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Car Rental (button)</name>
   <tag></tag>
   <elementGuidId>5305ae27-7028-440f-b082-112c740c7b72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div[3]/div[2]/div/div[2]/div/div/div/div/div[6]/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-901oao.r-jwli3a.r-t1w4ow.r-ubezar.r-b88u0q.r-135wba7.r-1jkjb.r-q4m81j</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a8a1b7f5-2239-4f87-9739-8e36631c41ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>7fc1f407-8e66-41d9-b187-452070e9e352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-901oao r-jwli3a r-t1w4ow r-ubezar r-b88u0q r-135wba7 r-1jkjb r-q4m81j</value>
      <webElementGuid>b88945c8-7c8f-4ecf-b942-8ddb74250b86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Car Rental</value>
      <webElementGuid>014c38c1-ae93-45f0-ae01-4fdedb74d642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;css-1dbjc4n r-aoullt r-6koalj r-1wtj0ep r-dg7iqi r-bnwqim r-13qz1uu r-tqpus0&quot;]/div[@class=&quot;css-1dbjc4n r-1ifxtd0 r-1jgb5lz r-1a83bov r-17yavnb&quot;]/div[@class=&quot;css-1dbjc4n r-bnwqim&quot;]/div[@class=&quot;css-1dbjc4n r-1wzrnnt r-6yljno r-bnwqim r-pezta&quot;]/div[@class=&quot;css-1dbjc4n r-kdyh1x r-xyw6el&quot;]/div[@class=&quot;css-1dbjc4n r-1wh2hl7 r-o8yidv r-5oul0u r-bnwqim r-184en5c&quot;]/div[@class=&quot;css-1dbjc4n r-bnwqim r-184en5c&quot;]/div[@class=&quot;css-1dbjc4n r-6koalj r-18u37iz r-9aw3ui&quot;]/div[@class=&quot;css-1dbjc4n r-1pi2tsx r-bnwqim r-184en5c&quot;]/div[@class=&quot;css-1dbjc4n r-11mg6pl r-1h84pjw r-rs99b7 r-1loqt21 r-18u37iz r-1pi2tsx r-ymttw5 r-5njf8e r-1otgn73 r-lrvibr&quot;]/div[@class=&quot;css-1dbjc4n r-18u37iz r-1777fci r-1mnahxq&quot;]/div[@class=&quot;css-901oao r-jwli3a r-t1w4ow r-ubezar r-b88u0q r-135wba7 r-1jkjb r-q4m81j&quot;]</value>
      <webElementGuid>d5d8fd3e-6c6f-45c5-8e62-68c3d197ddb1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div[3]/div[2]/div/div[2]/div/div/div/div/div[6]/div/div[2]/div</value>
      <webElementGuid>192f67e6-ac4b-44aa-8391-2f10919129a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Airport Transfer'])[2]/following::div[5]</value>
      <webElementGuid>2d9a28a6-6470-4dda-91a9-44c3c5e81b6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bus &amp; Travel'])[2]/following::div[10]</value>
      <webElementGuid>e4ecd0d9-7259-426a-8036-4d3fa7e5f522</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Things to Do'])[2]/preceding::div[2]</value>
      <webElementGuid>b3130f61-8431-498e-a724-9bf4fec83a18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More'])[2]/preceding::div[7]</value>
      <webElementGuid>5e7cb58e-e09a-4637-8302-5a7fb7fc8826</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div</value>
      <webElementGuid>3abce0fb-871f-42b4-ae38-b139f23c53bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Car Rental' or . = 'Car Rental')]</value>
      <webElementGuid>d75ef7b3-9484-468c-bb79-5df543680cfc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
