<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Drop-off Location text</name>
   <tag></tag>
   <elementGuidId>e246df54-02cf-453c-9ca3-de17fbcbec82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='RENTAL_DROPOFF_LOCATION']/div/div/div/h3</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-1dbjc4n.r-1ihkh82.r-kdyh1x.r-b4qz5r.r-1ifxtd0.r-nsbfu8.r-184en5c > div.css-1dbjc4n.r-eqz5dr > div.css-1dbjc4n.r-1awozwy.r-18u37iz.r-1h0z5md > h3.css-4rbku5.css-901oao.r-t1w4ow.r-ubezar.r-b88u0q.r-rjixqe.r-fdjqy7</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>215136bb-c078-41bd-9f0e-a8bd1b2d9e9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-level</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>04e54ee2-5c78-4883-8fa9-0b608814c7df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>c156592f-9341-4bcf-b897-3a56f89e86c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>heading</value>
      <webElementGuid>99b4ae6d-784f-416e-996f-6bb67f8f5536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-4rbku5 css-901oao r-t1w4ow r-ubezar r-b88u0q r-rjixqe r-fdjqy7</value>
      <webElementGuid>4ea3ef2b-80c8-4283-9cf3-aca0f8936d0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Drop-off Location*</value>
      <webElementGuid>2c0ccd88-68b3-4be8-8459-3ea3784aa540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RENTAL_DROPOFF_LOCATION&quot;)/div[@class=&quot;css-1dbjc4n r-1ihkh82 r-kdyh1x r-b4qz5r r-1ifxtd0 r-nsbfu8 r-184en5c&quot;]/div[@class=&quot;css-1dbjc4n r-eqz5dr&quot;]/div[@class=&quot;css-1dbjc4n r-1awozwy r-18u37iz r-1h0z5md&quot;]/h3[@class=&quot;css-4rbku5 css-901oao r-t1w4ow r-ubezar r-b88u0q r-rjixqe r-fdjqy7&quot;]</value>
      <webElementGuid>85f67705-88b1-41c5-a8bf-d76aef63d1a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RENTAL_DROPOFF_LOCATION']/div/div/div/h3</value>
      <webElementGuid>de510c07-b8bb-4382-8c41-7ddb795f08dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Train Station'])[3]/following::h3[1]</value>
      <webElementGuid>dd678314-0ba5-43b0-a275-75bbbb2438a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gambir, Central Jakarta, Jakarta, Indonesia, Southeast Asia, Asia'])[2]/following::h3[1]</value>
      <webElementGuid>47c6cba9-5b29-4e44-b6db-9e82f7855bee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rental Duration'])[1]/preceding::h3[2]</value>
      <webElementGuid>1dab8c76-fe8a-42cf-817a-8950d32c3dac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Drop-off Location']/parent::*</value>
      <webElementGuid>5c55ce17-9555-411f-88a5-db00d1476710</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/h3</value>
      <webElementGuid>77e0c92a-ff8d-4eb7-985c-a17e447ff9b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Drop-off Location*' or . = 'Drop-off Location*')]</value>
      <webElementGuid>4fce1d4d-b54c-4d43-b020-1c6ac49c4a00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
